# Generated by Django 4.1.3 on 2023-08-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_review_ticket_delete_blog_review_ticket_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.photo'),
        ),
    ]
