# Generated by Django 4.1.3 on 2023-08-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ticket_date_created_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='date_created_response',
        ),
    ]
