# Generated by Django 4.1.3 on 2023-08-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_userfollows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
