# Generated by Django 4.1.3 on 2023-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': "Ce nom d'utilisateur est déjà utilisé"}, max_length=100, unique=True),
        ),
    ]
