# Generated by Django 4.1.3 on 2023-07-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Cet email existe déjà dans notre base de données'}, max_length=100, unique=True),
        ),
    ]
